import * as fs from "fs";
import * as path from "path";

/**
 * Publishes every deployed contract's address + ABI into @hana/shared, so the worker and every
 * frontend read from one generated source instead of hand-copying addresses (WORKFLOW rule #1).
 *
 * Reads:  deployments/<network>.json  (this package)
 * Writes: packages/shared/src/generated/<network>.ts
 */

const CONTRACT_NAMES = [
  "IUSDC",
  "CreditRegistry",
  "LendingPool",
  "SettlementVault",
  "LoanManager",
  "CreditImporterASC",
] as const;

const deploymentsDir = path.join(__dirname, "..", "deployments");
const artifactsDir = path.join(__dirname, "..", "artifacts", "contracts");
const outDir = path.join(__dirname, "..", "..", "packages", "shared", "src", "generated");

function findArtifact(name: string): any {
  // walk artifacts/contracts/**/<name>.sol/<name>.json
  const stack = [artifactsDir];
  while (stack.length) {
    const dir = stack.pop()!;
    if (!fs.existsSync(dir)) continue;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name);
      if (entry.isDirectory()) stack.push(p);
      else if (entry.name === `${name}.json`) return JSON.parse(fs.readFileSync(p, "utf8"));
    }
  }
  throw new Error(`Artifact not found for ${name}. Run "pnpm build" first.`);
}

function main() {
  const files = fs.existsSync(deploymentsDir)
    ? fs.readdirSync(deploymentsDir).filter((f) => f.endsWith(".json"))
    : [];
  if (files.length === 0) {
    console.log("No deployments found yet — nothing to export.");
    return;
  }

  fs.mkdirSync(outDir, { recursive: true });

  for (const f of files) {
    const network = f.replace(/\.json$/, "");
    const rec = JSON.parse(fs.readFileSync(path.join(deploymentsDir, f), "utf8"));

    const contracts: Record<string, { address: string; abi: any[] }> = {};
    for (const name of CONTRACT_NAMES) {
      const entry = rec.contracts?.[name];
      if (!entry?.address) continue;
      const artifact = findArtifact(name);
      contracts[name] = { address: entry.address, abi: artifact.abi };
    }

    const outFile = path.join(outDir, `${network}.ts`);
    const body =
      `// AUTO-GENERATED by hana-ctc-contracts/scripts/export-abis.ts — do not edit by hand.\n` +
      `export const chainId = ${rec.chainId};\n` +
      `export const contracts = ${JSON.stringify(contracts, null, 2)} as const;\n`;
    fs.writeFileSync(outFile, body);
    console.log(`Wrote ${path.relative(process.cwd(), outFile)} (${Object.keys(contracts).length} contracts)`);
  }
}

main();
